export const imgs = [
  require("../assets/images/banner1.png"),
  require("../assets/images/banner2.png"),
  require("../assets/images/banner3.png"),
  require("../assets/images/banner1.png"),
  require("../assets/images/banner2.png"),
];

export const categories = [
  "All",
  "Running",
  "Sneakers",
  "Casual",
  "Formal",
  "Boots",
  "Sports",
];

export const shoesData = [
  {
    imgLink: require("../assets/images/shoe1.png"),
    name: "Nike Air Max 270",
    shoeCategory: "Running",
    price: "$150",
    mrp: "$200",
    rating: 4.8,
  },
  {
    imgLink: require("../assets/images/shoe2.png"),
    name: "Adidas Ultraboost 22",
    shoeCategory: "Running",
    price: "$180",
    mrp: "$220",
    rating: 4.7,
  },
  {
    imgLink: require("../assets/images/shoe3.png"),
    name: "Jordan Air 1 Retro High",
    shoeCategory: "Basketball",
    price: "$170",
    mrp: "$210",
    rating: 4.9,
  },
  {
    imgLink: require("../assets/images/shoe4.png"),
    name: "Converse Chuck Taylor All Star",
    shoeCategory: "Casual",
    price: "$55",
    mrp: "$70",
    rating: 4.3,
  },
  {
    imgLink: require("../assets/images/shoe1.png"),
    name: "Vans Old Skool",
    shoeCategory: "Skateboarding",
    price: "$65",
    mrp: "$80",
    rating: 4.5,
  },
  {
    imgLink: require("../assets/images/shoe2.png"),
    name: "New Balance 990v5",
    shoeCategory: "Running",
    price: "$185",
    mrp: "$230",
    rating: 4.6,
  },
  {
    imgLink: require("../assets/images/shoe3.png"),
    name: "Puma RS-X3",
    shoeCategory: "Lifestyle",
    price: "$90",
    mrp: "$120",
    rating: 4.2,
  },
  {
    imgLink: require("../assets/images/shoe4.png"),
    name: "Reebok Club C 85",
    shoeCategory: "Casual",
    price: "$75",
    mrp: "$95",
    rating: 4.4,
  },
  {
    imgLink: require("../assets/images/shoe1.png"),
    name: "Under Armour HOVR Phantom 3",
    shoeCategory: "Running",
    price: "$130",
    mrp: "$160",
    rating: 4.3,
  },
  {
    imgLink: require("../assets/images/shoe2.png"),
    name: "ASICS Gel-Kayano 29",
    shoeCategory: "Running",
    price: "$160",
    mrp: "$200",
    rating: 4.7,
  },
  {
    imgLink: require("../assets/images/shoe3.png"),
    name: "Nike React Infinity Run Flyknit 3",
    shoeCategory: "Running",
    price: "$160",
    mrp: "$195",
    rating: 4.6,
  },
  {
    imgLink: require("../assets/images/shoe4.png"),
    name: "Adidas Stan Smith",
    shoeCategory: "Casual",
    price: "$85",
    mrp: "$100",
    rating: 4.5,
  },
  {
    imgLink: require("../assets/images/shoe1.png"),
    name: "Air Jordan 11 Retro",
    shoeCategory: "Basketball",
    price: "$220",
    mrp: "$270",
    rating: 4.9,
  },
  {
    imgLink: require("../assets/images/shoe2.png"),
    name: "Timberland 6-Inch Premium Boot",
    shoeCategory: "Boots",
    price: "$190",
    mrp: "$230",
    rating: 4.8,
  },
  {
    imgLink: require("../assets/images/shoe3.png"),
    name: "Dr. Martens 1460 Original",
    shoeCategory: "Boots",
    price: "$170",
    mrp: "$200",
    rating: 4.7,
  },
  {
    imgLink: require("../assets/images/shoe4.png"),
    name: "Allbirds Tree Runners",
    shoeCategory: "Casual",
    price: "$98",
    mrp: "$115",
    rating: 4.4,
  },
  {
    imgLink: require("../assets/images/shoe1.png"),
    name: "Brooks Ghost 15",
    shoeCategory: "Running",
    price: "$140",
    mrp: "$175",
    rating: 4.6,
  },
  {
    imgLink: require("../assets/images/shoe2.png"),
    name: "Skechers Max Cushioning Elite",
    shoeCategory: "Walking",
    price: "$85",
    mrp: "$110",
    rating: 4.3,
  },
  {
    imgLink: require("../assets/images/shoe3.png"),
    name: "Nike Air Force 1 '07",
    shoeCategory: "Casual",
    price: "$90",
    mrp: "$115",
    rating: 4.7,
  },
  {
    imgLink: require("../assets/images/shoe4.png"),
    name: "Hoka One One Clifton 9",
    shoeCategory: "Running",
    price: "$130",
    mrp: "$160",
    rating: 4.8,
  },
];
